# Generated by Django 3.1.6 on 2022-04-30 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100, verbose_name='origin')),
                ('destination', models.CharField(max_length=100, verbose_name='destination')),
                ('dim_1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='dim_1')),
                ('dim_2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='dim_2')),
                ('business_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='business_key')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
            ],
            options={
                'verbose_name': 'Data Point',
                'verbose_name_plural': 'Data Points',
                'ordering': ['id'],
            },
        ),
    ]
