# Generated by Django 3.1.6 on 2022-04-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='is_train',
            field=models.BooleanField(default=False, verbose_name='is_train'),
        ),
    ]
