# Generated by Django 3.1.6 on 2022-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datapoint_is_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='n_contours',
            field=models.IntegerField(blank=True, null=True, verbose_name='n_contours'),
        ),
    ]
