# Generated by Django 3.1.6 on 2022-04-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datapoint_n_contours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='n_contours',
            field=models.IntegerField(default=-1, verbose_name='n_contours'),
        ),
    ]
